### ISSUE TITLE
Wifi Client count not showing clients when using capsman

### ISSUE THREAD

**Issue by darks00ul** [IgorKha/Grafana-Mikrotik#10]
Hi there, I love this dashboard and is one my first Grafana / Prometheus, so I'm not so experienced yet customizing on my own.
With this said, is there any chance on kindly taking into consideration these two request:

1) Add wifi client count support on the main view of the dashboard when using capsman, without capsman this works just fine but with capsman I see the client count as zero.
![imagen](https://user-images.githubusercontent.com/83095497/153718753-51382962-fe33-4d78-a7a5-8e0fc67227dc.png)

2) In the wireless tab there is a cool graph showing the historic level of signal of the customers, is there anyway to replicate this in the capsman tab?

**Comment by IgorKha** [comment]
Hey! thanks :)
1. there is a separate tab for capsman, you can move it up
2. No, Mikrotik does not provide such an opportunity.

**Comment by darks00ul** [comment]
Hi Igor,

I understand and thanks for taking your time to respond!

Great job with this dashboard by the way! I love it...
