### ISSUE TITLE
PPP Interface Not Disaplaying TX/RX Sum

### ISSUE THREAD

**Issue by Gosokan** [IgorKha/Grafana-Mikrotik#18]
PPPoE interface (pppoe-out1) not diplaying Rx Sum and TX Sum

![Grafana-Mikrotik-Interface](https://user-images.githubusercontent.com/13587422/183016402-5460eedd-9644-416f-9675-7a158a912785.png)

**Comment by IgorKha** [comment]
unfortunately Mikrotik does not transmit this information via snmp :(
![Screenshot_20220806_115024](https://user-images.githubusercontent.com/2268209/183242101-e86382d7-40f6-458d-b610-68001d9441d1.png)
