### ISSUE TITLE
K8S issue

### ISSUE THREAD

**Issue by jr0dd** [IgorKha/Grafana-Mikrotik#2]
First off, thank you for your work on this. I'm just having issues with the dashboard when running this on my k8s cluster. More than likely a relabeling issue and I am not quite sure how to address it to be completely honest. My router is on IP 10.10.0.1 but the container IP is 172.16.0.66. I only have one relabeling, but the dashboard is showing a lot of duplicate entries. I'm definitely a noob at grafana/prometheus so hoping you could maybe point me in the right direction.

relabelings:
```
- sourceLabels: [__param_target]
    targetLabel: instance
```

screenshot:
![Screen Shot 2021-07-20 at 12 57 12 PM](https://user-images.githubusercontent.com/285797/126366559-87ca9243-a27b-471f-9390-741dfaa18dd0.jpg)

**Comment by IgorKha** [comment]
Hey! I don't think that is a problem of the dashboard, but it might relate to the configuration of the prometheus for k8s.
Here you may try to find a key to the issue: https://github.com/prometheus-operator/prometheus-operator/issues/1928 
Unfortunately, I am not really familiar with k8s, so this is all i could suggest

**Comment by jr0dd** [comment]
yeah definitely an issue with the labelings. i'll play around with it more later

**Comment by jr0dd** [comment]
So what happened was it was just the old metrics data overlapping. I kept reinstalling the pod when I was testing my config. I did need to use the transform of `Series to Row` with a value of Max on a couple of the panels because my router is a dual core and would show duplicate entries and I added `CPU {{hrDeviceIndex}}` for the legend on the CPU Load panel to list CPU numbers.
