### ISSUE TITLE
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

### ISSUE THREAD

**Issue by helospro** [IgorKha/Grafana-Mikrotik#20]
Hello, 
i got some error "error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY` "
![Screenshot from 2022-09-12 14-03-40](https://user-images.githubusercontent.com/100141161/189592838-a01bac9d-9c9e-4dc1-acf6-1bd566742382.png)

**Comment by IgorKha** [comment]
I'm not sure why you're having problems, but as Google says - installation according to the docker instructions helps
[click](https://docs.docker.com/compose/install/linux/)
other docker-compose files work for you?

**Comment by helospro** [comment]
This works: sudo apt remove golang-docker-credential-helpers
