### ISSUE TITLE
which Prometheus Exporter used?

### ISSUE THREAD

**Issue by PackElend** [IgorKha/Grafana-Mikrotik#21]
can you tell which Prometheus Exporter for Mikrotik RouterOS is used?
I have found a few so far, which all have some issues, so it would be nice to know, which limitation the one used her has.

I have found so far:
- https://github.com/akpw/mktxp
- https://github.com/nshttpd/mikrotik-exporter
- https://github.com/prometheus/snmp_exporter
- yours: https://hub.docker.com/r/mashinkopochinko/snmp_exporter_mikrotik

**Comment by yyovkov** [comment]
I succeed make this one running with 
https://github.com/prometheus/snmp_exporter
