### ISSUE TITLE
Error reading Prometheus: Post "http://mk_prometheus:9090/api/v1/query": dial tcp: lookup mk_prometheus: Try again

### ISSUE THREAD

**Issue by helospro** [IgorKha/Grafana-Mikrotik#26]
![image](https://user-images.githubusercontent.com/100141161/202409723-07e24cb7-d056-4ce0-842e-bdac7c0b9677.png)
![image](https://user-images.githubusercontent.com/100141161/202409788-2635377c-9117-4b65-9b84-79072dcf08ee.png)

hello, i getting some error.
why prometheus status always restarting ?

**Comment by IgorKha** [comment]
hello
maybe port is busy ?
watch container log `docker logs -f  <container id or name>`

**Comment by helospro** [comment]
![image](https://user-images.githubusercontent.com/100141161/202613148-058077fc-0b66-4d0a-adff-81be39e0d264.png)

docker logs -f  mk_prometheus

**Comment by helospro** [comment]
fixed !!
im using "Tab" when insert new targets it's should use "space"
