### ISSUE TITLE
Wi-Fi Clients panel doesn't work

### ISSUE THREAD

**Issue by MarkVorkosigan** [IgorKha/Grafana-Mikrotik#3]
Wi-Fi Clients panel doesn't work. If I try to open Transform rules of this dashboard I get error: Undefined: SortBy.
![transform](https://user-images.githubusercontent.com/4159295/129019511-7d1076c3-0f43-485b-8888-6ffcac6fa2ac.png)

When I enter this dashboard I get this errors:
![template](https://user-images.githubusercontent.com/4159295/129019242-db7cd522-f242-46e1-b2b9-e1704bfe3d51.png)

**Comment by IgorKha** [comment]
Hey!  what version of grafana are you using?  try updating grafana >= 7.5.5 and run the latest dashboard

**Comment by MarkVorkosigan** [comment]
It's 7.2.0 version.

**Comment by MarkVorkosigan** [comment]
I've updated Grafana to 7.5.10 version and reimported dashboard. Now it looks like this.
![3](https://user-images.githubusercontent.com/4159295/129153775-8939f6a8-82f6-4672-9a59-bd72bc876bc5.png)

**Comment by IgorKha** [comment]
1. find `1.3.6.1.4.1.14988.1.1.1.2.1.12` in `http://ip_SNMP_exporter:9116/snmp?module=mikrotik&target=youRouterIp`
or show
http://IP_PROMETHEUS:9090/graph?g0.expr=mtxrWlRtabSignalToNoise&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h

Show me output `snmpwalk -v 2c -c public youRouterIp 1.3.6.1.4.1.14988.1.1.1.2.1.12`

I tested grafana 7.5.10 in docker (grafana/grafana:7.5.10) - everything works.
![Screen Shot 2021-08-12 at 23 00 08](https://user-images.githubusercontent.com/2268209/129264065-65ce6b81-e424-4a7e-b44e-8b5702b46f66.png)

**Comment by MarkVorkosigan** [comment]
You're right - it works.
