### ISSUE TITLE
mk_prometheus container in Starting status

### ISSUE THREAD

**Issue by djgamebeat** [IgorKha/Grafana-Mikrotik#30]
**After launch, some of the containers start, but this one cannot. Please help me get started. Console output below.**

[root@ww Grafana-Mikrotik]# bash run.sh --config

====================================

Prometheus

Change target mikrotik IP address ? (current 192.168.3.1) [Y/n]
Enter target mikrotik IP address: 192.168.3.30

... Prometheus target IP changed to 192.168.3.30

====================================

Grafana

Change default credentials Grafana ? [y/N]
Default Grafana:
            User: admin
            Password: mikrotik
[+] Building 0.0s (0/0)
[+] Running 2/3
 ✔ Container mk_grafana Running                                                                                                                                                                  0.0s
 ⠿ Container mk_prometheus     Starting                                                                                                                                                                     43516.2s
 ✔ Container mk_snmp_exporter  Recreated                                                                                                                                                                        0.3s
^Z
[3]+  Stopped                 bash run.sh --config

**Comment by IgorKha** [comment]
Is this problem still relevant?
