### ISSUE TITLE
dial tcp: lookup mk_snmp_exporter on 127.0.0.11:53: server misbehaving

### ISSUE THREAD

**Issue by kuroro750** [IgorKha/Grafana-Mikrotik#31]
Hai excus me,
may i know whats wrong with may prometheus
i follow the step clearly like the tutorial but i got the error.
![1,2](https://github.com/IgorKha/Grafana-Mikrotik/assets/144130452/7cd70cb9-6f2e-4c7e-867c-e3237be1fd80)
![1,3](https://github.com/IgorKha/Grafana-Mikrotik/assets/144130452/3b3bfac0-9a18-4a50-b033-09a7b388019a)

**Comment by CyberPips-EO** [comment]
Having similar issue. snmp_exporter container constantly restarting

**Comment by massgame** [comment]
i think that's because snmp_exporter's configuration format changed. (https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md)

after modifying snmp.yml, it works without issue. (https://github.com/IgorKha/Grafana-Mikrotik/pull/32)

**Comment by CyberPips-EO** [comment]
> i think that's because snmp_exporter's configuration format changed. (https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md)
> 
> after modifying snmp.yml, it works without issue. (#32)

Perfect. Thank you

**Comment by IgorKha** [comment]
f741901f03dab2e4c51618d4905379a4aa33f546 #32 
thank you @massgame
